name: RocketPropelledMinecarts
main: wa.was.rpm.RocketPropelledMinecarts
version: 0.0.3
api-version: 1.20
commands:
  rpmdebug:
    description: Enable Rocket Propelled Minecarts debug in console
    usage: rpmdebug
permissions:
  rpm.boost:
    description: Allows use of rockets in minecarts
    default: true
